apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: delightdavid-cert
spec:
  secretName: delightdavid-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: delightdavid.org.ng
  dnsNames:
  - delightdavid.org.ng
